/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaanapp.tubes.GUI;

/**
 *
 * @author Irfan Gerard W M
 */
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import perpustakaanapp.tubes.Model.AnggotaModel;
import perpustakaanapp.tubes.Model.BukuModel;
import perpustakaanapp.tubes.Model.KategoriModel;
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    DefaultTableModel tabel;
    AnggotaModel am = new AnggotaModel();
    List<AnggotaModel> dataAnggota = new ArrayList<>();
    String JK;
    public Admin() {
        initComponents();
        bersihText();
        siapIsi(false);
        Tambah.setEnabled(true);
        Simpan.setEnabled(false);
        Hapus.setEnabled(false);
        Edit.setEnabled(false);
        Keluar.setEnabled(true);
        buatTabel();
        tampilTabel();
        setLocationRelativeTo(null);
    }
    private void bersihText() {
        txtNO.setText(null);
        cmbJK.setSelectedItem(null);
        txtNama.setText(null);
        txtTelp.setText(null);
        txtAlamat.setText(null);
    }
    private void siapIsi(boolean x) {
        txtNO.setEnabled(x);
        cmbJK.setEnabled(x);
        txtNama.setEnabled(x);
        txtTelp.setEnabled(x);
        txtAlamat.setEnabled(x);
    }

    private void buatTabel() {
        tabel = new DefaultTableModel();
        tabel.addColumn("NO");
        tabel.addColumn("Nama Anggota");
        tabel.addColumn("Jenis Kelamin");
        tabel.addColumn("Telpon");
        tabel.addColumn("Alamat");
        tblAnggota.setModel(tabel);
        //Untuk mengatur lebar kolom
        tblAnggota.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);                
        tblAnggota.getColumnModel().getColumn(0).setPreferredWidth(80);
        tblAnggota.getColumnModel().getColumn(1).setPreferredWidth(100);        
        tblAnggota.getColumnModel().getColumn(2).setPreferredWidth(80); 
        tblAnggota.getColumnModel().getColumn(3).setPreferredWidth(100); 
        tblAnggota.getColumnModel().getColumn(4).setPreferredWidth(120); 
    }
    private void tampilTabel() {
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        dataAnggota.clear();
        dataAnggota = am.tampil();
        for (int x = 0; x < dataAnggota.size(); x++) {
            Object[] data = new Object[5];
            data[0] = dataAnggota.get(x).getNo();
            data[1] = dataAnggota.get(x).getNama();
            data[2] = dataAnggota.get(x).getJk();
            data[3] = dataAnggota.get(x).getTelp();
            data[4] = dataAnggota.get(x).getAlamat();
            tabel.addRow(data);
        }
    }

    private void buatKode() {
        String kode;
        dataAnggota.clear();
        dataAnggota = am.tampil();
        if (dataAnggota.isEmpty()) {
            kode = "A-1";
            txtNO.setText(kode);
        } else {
            int no_urut = Integer.parseInt(dataAnggota.get(0).getNo().substring(2)) + 1;
            kode = "A-" + no_urut;
            txtNO.setText(kode);
        }
    }
    private void isijk(){
        AnggotaModel nw = new AnggotaModel();
        if(cmbJK.getSelectedItem()== "---Pilih---"){
        JK = "";
        }else if (cmbJK.getSelectedItem()=="Laki - Laki"){
          JK =   "Laki - Laki";
        } else if (cmbJK.getSelectedItem() == "Perempuan"){
            JK= "Perempuan";
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CmbKategori = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Kodebuku = new javax.swing.JLabel();
        txtNO = new javax.swing.JTextField();
        NamaAnggota = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        NamaAnggota1 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        NamaAnggota2 = new javax.swing.JLabel();
        NamaAnggota3 = new javax.swing.JLabel();
        txtTelp = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        Tambah = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        cmbJK = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnggota = new javax.swing.JTable();

        jButton1.setText("jButton1");

        CmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbKategori.setSelectedIndex(-1);
        CmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbKategoriActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Admin");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        Kodebuku.setText("No. Anggota");

        txtNO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNOActionPerformed(evt);
            }
        });

        NamaAnggota.setText("Nama Anggota");

        NamaAnggota1.setText("Alamat");

        NamaAnggota2.setText("Jenis Kelamin");

        NamaAnggota3.setText("Nomer Hp");

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(Tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Edit)
                .addGap(5, 5, 5)
                .addComponent(Keluar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(Simpan)
                    .addComponent(Hapus)
                    .addComponent(Edit)
                    .addComponent(Keluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cmbJK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Pilih --", "Laki - Laki", "Perempuan" }));

        tblAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAnggotaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAnggota);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaAnggota)
                                    .addComponent(NamaAnggota1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                    .addComponent(txtAlamat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NamaAnggota2)
                                    .addComponent(NamaAnggota3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelp)
                                    .addComponent(cmbJK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Kodebuku)
                                .addGap(20, 20, 20)
                                .addComponent(txtNO, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kodebuku)
                    .addComponent(txtNO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaAnggota)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaAnggota2)
                    .addComponent(cmbJK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NamaAnggota1)
                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NamaAnggota3)
                    .addComponent(txtTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbKategoriActionPerformed
        // TODO add your handling code here:
        AnggotaModel nw = new AnggotaModel();
        List<AnggotaModel> data = new ArrayList<>();
        try {
            data = nw.cariAnggota(CmbKategori.getSelectedItem().toString());
            txtNO.setText(data.get(0).getId());
        } catch (Exception x) {

        }
    }//GEN-LAST:event_CmbKategoriActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int baris=tblAnggota.getSelectedRow();
        am.setId(tblAnggota.getModel().getValueAt(baris, 0).toString());
        am.hapus();
        bersihText();
        tampilTabel();
    }//GEN-LAST:event_HapusActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
        if (Edit.getText().equalsIgnoreCase("edit")) {
            Edit.setText("Batal");
            siapIsi(true);
            Tambah.setEnabled(false);
            Simpan.setEnabled(true);
            Hapus.setEnabled(false);
            Edit.setEnabled(true);
            Keluar.setEnabled(false);
        } else {
            Edit.setText("Edit");
            bersihText();
            siapIsi(false);
            Tambah.setEnabled(true);
            Simpan.setEnabled(false);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(true);
        }
    }//GEN-LAST:event_EditActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        if(txtNO.getText().isEmpty()|| txtNama.getText().isEmpty()|| txtAlamat.getText().isEmpty()||txtTelp.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "data kurang lengkap");
        }else {
            am.getNo(txtNO.getText());
            am.getNama(txtNama.getText());
            am.getAlamat(txtAlamat.getText());
            am.getTelp(txtTelp.getText());
            am.setJk(JK);
            if(Tambah.getText().equalsIgnoreCase("Tambah")){
                am.tambah();
            }else if(Edit.getText().equalsIgnoreCase("batal")){
                am.setNo(txtNO.getText());
                am.edit();
            }
            bersihText();
            siapIsi(false);
            tampilTabel();
            Tambah.setEnabled(true); 
            Simpan.setEnabled(false);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(true);
            Tambah.setText("Tambah");
            Edit.setText("Edit");
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        if (Tambah.getText().equalsIgnoreCase("tambah")) {
            Tambah.setText("Batal");
            bersihText();
            siapIsi(true);
            Tambah.setEnabled(true);
            Simpan.setEnabled(true);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(false);
        } else {
            Tambah.setText("Tambah");
            bersihText();
            siapIsi(false);
            Tambah.setEnabled(true);
            Simpan.setEnabled(false);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(true);
        }
    }//GEN-LAST:event_TambahActionPerformed

    private void tblAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAnggotaMouseClicked
        // TODO add your handling code here:
        int baris=tblAnggota.getSelectedRow();        
        txtNO.setText(tblAnggota.getModel().getValueAt(baris, 0).toString());
        txtNama.setText(tblAnggota.getModel().getValueAt(baris, 1).toString());
        cmbJK.setSelectedItem(tblAnggota.getModel().getValueAt(baris, 2).toString());
        txtTelp.setText(tblAnggota.getModel().getValueAt(baris, 3).toString());
        txtAlamat.setText(tblAnggota.getModel().getValueAt(baris, 4).toString());
        
        Tambah.setText("Tambah");
        Edit.setText("Edit");
        Tambah.setEnabled(true);
        Simpan.setEnabled(false);
        Hapus.setEnabled(true);
        Edit.setEnabled(true);
        Keluar.setEnabled(true);
    }//GEN-LAST:event_tblAnggotaMouseClicked

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    private void txtNOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbKategori;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Keluar;
    private javax.swing.JLabel Kodebuku;
    private javax.swing.JLabel NamaAnggota;
    private javax.swing.JLabel NamaAnggota1;
    private javax.swing.JLabel NamaAnggota2;
    private javax.swing.JLabel NamaAnggota3;
    private javax.swing.JButton Simpan;
    private javax.swing.JButton Tambah;
    private javax.swing.JComboBox<String> cmbJK;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblAnggota;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNO;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelp;
    // End of variables declaration//GEN-END:variables
}
