/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpustakaanapp.tubes.GUI;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import perpustakaanapp.tubes.Model.BukuModel;
import perpustakaanapp.tubes.Model.KategoriModel;
/**
 *
 * @author Irfan Gerard W M
 */
public class MBuku extends javax.swing.JFrame {

    DefaultTableModel tabel;
    BukuModel bm = new BukuModel();
    List<BukuModel> dataBuku = new ArrayList<>();
    /**
     * Creates new form MBuku
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public MBuku() {
        initComponents();
        bersihText();
        siapIsi(false);
        Tambah.setEnabled(true);
        Simpan.setEnabled(false);
        Hapus.setEnabled(false);
        Edit.setEnabled(false);
        Keluar.setEnabled(true);
        isiKategori();
        buatTabel();
        tampilTabel();
        ID.setVisible(true);
        txtIdBuku.setVisible(true);
        setLocationRelativeTo(null);
    }

    private void bersihText() {
        Kode.setText(null);
        CmbKategori.setSelectedItem(null);
        Judul.setText(null);
        Pengarang.setText(null);
        Penerbit.setText(null);
        ISBN.setText(null);
        Stock.setText(null);
    }

    private void siapIsi(boolean x) {
        Kode.setEnabled(x);
        CmbKategori.setEnabled(x);
        Judul.setEnabled(x);
        Pengarang.setEnabled(x);
        Penerbit.setEnabled(x);
        ISBN.setEnabled(x);
        Stock.setEnabled(x);
    }

    private void isiKategori() {
        List<KategoriModel> data = new ArrayList<>();
        KategoriModel km = new KategoriModel();
        data = km.tampil();
        if (data.isEmpty()) {
            CmbKategori.setSelectedItem(null);
        } else {
            for (int a = 0; a < data.size(); a++) {
                CmbKategori.addItem(data.get(a).getNama());
            }
        }
    }

    private void buatTabel() {
        tabel = new DefaultTableModel();
        tabel.addColumn("ID");
        tabel.addColumn("Kode");
        tabel.addColumn("Judul");
        tabel.addColumn("Pengarang");
        tabel.addColumn("Penerbit");
        tabel.addColumn("ISBN");
        tabel.addColumn("Stok");
        tabel.addColumn("Kategori_Id");
        tabel.addColumn("Kategori");
        tblBuku.setModel(tabel);
        //Untuk mengatur lebar kolom
        tblBuku.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);                
        tblBuku.getColumnModel().getColumn(0).setPreferredWidth(0);
        tblBuku.getColumnModel().getColumn(1).setPreferredWidth(100);        
        tblBuku.getColumnModel().getColumn(2).setPreferredWidth(200); 
        tblBuku.getColumnModel().getColumn(3).setPreferredWidth(150); 
        tblBuku.getColumnModel().getColumn(4).setPreferredWidth(150);
        tblBuku.getColumnModel().getColumn(5).setPreferredWidth(100);        
        tblBuku.getColumnModel().getColumn(6).setPreferredWidth(100); 
        tblBuku.getColumnModel().getColumn(7).setPreferredWidth(0);         
        tblBuku.getColumnModel().getColumn(8).setPreferredWidth(100);  
    }

    private void tampilTabel() {
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        dataBuku.clear();
        dataBuku = bm.tampil();
        for (int x = 0; x < dataBuku.size(); x++) {
            Object[] data = new Object[9];
            data[0] = dataBuku.get(x).getId();
            data[1] = dataBuku.get(x).getKode();
            data[2] = dataBuku.get(x).getJudul();
            data[3] = dataBuku.get(x).getPengarang();
            data[4] = dataBuku.get(x).getPenerbit();
            data[5] = dataBuku.get(x).getIsbn();
            data[6] = dataBuku.get(x).getStok();
            data[7] = dataBuku.get(x).getKategori_id();
            data[8] = dataBuku.get(x).getNama_kategori();
            tabel.addRow(data);
        }
    }

    private void buatKode() {
        String kd_kategori = CmbKategori.getSelectedItem().toString().substring(0, 3);
        String penerbit = Penerbit.getText().substring(0, 3);
        String pengarang = Pengarang.getText().substring(0, 3);
        String kode;
        dataBuku.clear();
        dataBuku = bm.tampil();
        if (dataBuku.isEmpty()) {
            kode = kd_kategori + "-" + penerbit + "-" + pengarang + "-1";
            Kode.setText(kode);
        } else {
            int no_urut = Integer.parseInt(dataBuku.get(0).getKode().substring(12)) + 1;
            kode = kd_kategori + "-" + penerbit + "-" + pengarang + "-" + no_urut;
            Kode.setText(kode);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();
        txtIdBuku = new javax.swing.JTextField();
        Kodebuku = new javax.swing.JLabel();
        Kode = new javax.swing.JTextField();
        Kategoribuku = new javax.swing.JLabel();
        CmbKategori = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        Judul = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Pengarang = new javax.swing.JTextField();
        Kategoribuku1 = new javax.swing.JLabel();
        Penerbit = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ISBN = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Stock = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        Tambah = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("Data Buku");

        txtIdBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(84, 84, 84)
                .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Kodebuku.setText("Kode Buku");

        Kategoribuku.setText("Katrgori Buku");

        CmbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CmbKategori.setSelectedIndex(-1);
        CmbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CmbKategoriActionPerformed(evt);
            }
        });

        jLabel2.setText("Judul");

        jLabel3.setText("Pengarang");

        Kategoribuku1.setText("Penerbit");

        jLabel4.setText("ISBN");

        ISBN.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ISBNKeyTyped(evt);
            }
        });

        jLabel5.setText("Stock");

        Stock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                StockKeyTyped(evt);
            }
        });

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Simpan.setText("Simpan");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });

        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Tambah)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Simpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Hapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Edit)
                .addGap(5, 5, 5)
                .addComponent(Keluar)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah)
                    .addComponent(Simpan)
                    .addComponent(Hapus)
                    .addComponent(Edit)
                    .addComponent(Keluar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kodebuku)
                                    .addComponent(jLabel2))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Kode, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(89, 89, 89)
                                        .addComponent(Kategoribuku)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CmbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(Judul)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(43, 43, 43))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(105, 105, 105)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kategoribuku1)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Penerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                    .addComponent(Stock))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Kodebuku)
                    .addComponent(Kode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kategoribuku)
                    .addComponent(CmbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Penerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Kategoribuku1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(Stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4)
                    .addComponent(ISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void CmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CmbKategoriActionPerformed
        // TODO add your handling code here:
        KategoriModel km = new KategoriModel();
        List<KategoriModel> data = new ArrayList<>();
        try {
            data = km.cariIdKategori(CmbKategori.getSelectedItem().toString());
            ID.setText(data.get(0).getId());
        } catch (Exception x) {

        }
    }//GEN-LAST:event_CmbKategoriActionPerformed

    
    private void txtIdBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdBukuActionPerformed

    private void StockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StockKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && Stock.getText().length() < 3
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_StockKeyTyped

    private void ISBNKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ISBNKeyTyped
        // TODO add your handling code here:
         char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') && ISBN.getText().length() < 15
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE) || (c == KeyEvent.VK_ENTER))) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ISBNKeyTyped

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        int baris=tblBuku.getSelectedRow();        
        txtIdBuku.setText(tblBuku.getModel().getValueAt(baris, 0).toString());         
        Kode.setText(tblBuku.getModel().getValueAt(baris, 1).toString());         
        Judul.setText(tblBuku.getModel().getValueAt(baris, 2).toString()); 
        Pengarang.setText(tblBuku.getModel().getValueAt(baris, 3).toString());         
        Penerbit.setText(tblBuku.getModel().getValueAt(baris, 4).toString()); 
        ISBN.setText(tblBuku.getModel().getValueAt(baris, 5).toString());         
        Stock.setText(tblBuku.getModel().getValueAt(baris, 6).toString()); 
        ID.setText(tblBuku.getModel().getValueAt(baris, 7).toString());         
        CmbKategori.setSelectedItem(tblBuku.getModel().getValueAt(baris, 8).toString());         
        Tambah.setText("Tambah");
        Edit.setText("Edit");
        Tambah.setEnabled(true);
        Simpan.setEnabled(false);
        Hapus.setEnabled(true);
        Edit.setEnabled(true);
        Keluar.setEnabled(true);
    }//GEN-LAST:event_tblBukuMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
        int baris=tblBuku.getSelectedRow();  
        bm.setId(tblBuku.getModel().getValueAt(baris, 0).toString());
        bm.hapus();
        bersihText();
        tampilTabel();
    }//GEN-LAST:event_HapusActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        // TODO add your handling code here:
         if (Edit.getText().equalsIgnoreCase("edit")) {
            Edit.setText("Batal");            
            siapIsi(true);
            Tambah.setEnabled(false);
            Simpan.setEnabled(true);
            Hapus.setEnabled(false);
            Edit.setEnabled(true);
            Keluar.setEnabled(false);
        } else {
            Edit.setText("Edit");
            bersihText();
            siapIsi(false);
            Tambah.setEnabled(true);
            Simpan.setEnabled(false);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(true);
        }        
    }//GEN-LAST:event_EditActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        if (Tambah.getText().equalsIgnoreCase("tambah")) {
            Tambah.setText("Batal");
            bersihText();
            siapIsi(true);
            Tambah.setEnabled(true);
            Simpan.setEnabled(true);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(false);
        } else {
            Tambah.setText("Tambah");
            bersihText();
            siapIsi(false);
            Tambah.setEnabled(true);
            Simpan.setEnabled(false);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(true);
        }
    }                                         

    private void cmbKategoriActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        KategoriModel km = new KategoriModel();
        List<KategoriModel> data = new ArrayList<>();
        try {
            data = km.cariIdKategori(CmbKategori.getSelectedItem().toString());
            ID.setText(data.get(0).getId());
        } catch (Exception x) {

        }
    }                                           

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        dispose();
    }                                         

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        
    }//GEN-LAST:event_TambahActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        // TODO add your handling code here:
        if (ID.getText().isEmpty() || Penerbit.getText().isEmpty()
                || Pengarang.getText().isEmpty() || Stock.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Lengkapi inputan buku");
        } else {
            buatKode();
            bm.setKode(Kode.getText());
            bm.setJudul(Judul.getText());
            bm.setPengarang(Pengarang.getText());
            bm.setPenerbit(Penerbit.getText());
            bm.setIsbn(ISBN.getText());
            bm.setStok(Stock.getText());
            bm.setKategori_id(ID.getText());
            if (Tambah.getText().equalsIgnoreCase("batal")) {
                bm.tambah();
            } else if (Edit.getText().equalsIgnoreCase("batal")) {
                bm.setId(txtIdBuku.getText());
                bm.edit();
            }
            bersihText();
            siapIsi(false);
            tampilTabel();
            Tambah.setEnabled(  true); 
            Simpan.setEnabled(false);
            Hapus.setEnabled(false);
            Edit.setEnabled(false);
            Keluar.setEnabled(true);
            Tambah.setText("Tambah");
            Edit.setText("Edit");
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_KeluarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MBuku().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CmbKategori;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField ISBN;
    private javax.swing.JTextField Judul;
    private javax.swing.JLabel Kategoribuku;
    private javax.swing.JLabel Kategoribuku1;
    private javax.swing.JButton Keluar;
    private javax.swing.JTextField Kode;
    private javax.swing.JLabel Kodebuku;
    private javax.swing.JTextField Penerbit;
    private javax.swing.JTextField Pengarang;
    private javax.swing.JButton Simpan;
    private javax.swing.JTextField Stock;
    private javax.swing.JButton Tambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtIdBuku;
    // End of variables declaration//GEN-END:variables
}
